# Generated by Django 4.0.1 on 2022-05-31 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stockProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='idCategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.categoria'),
            preserve_default=False,
        ),
    ]
