# Generated by Django 4.0.1 on 2022-06-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precioProducto',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='idCategoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='frontend.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1, verbose_name='Stock Producto'),
            preserve_default=False,
        ),
    ]
