# Generated by Django 4.0.1 on 2022-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idFoto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Foto')),
                ('nombreFoto', models.CharField(max_length=100, verbose_name='Nombre Foto')),
                ('nombreArchivo', models.CharField(max_length=256, verbose_name='Nombre Archivo')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('fechaPublicacion', models.DateField(verbose_name='Fecha Publicacion')),
            ],
        ),
    ]
