# Generated by Django 4.0.1 on 2022-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_rename_precioproducto_producto_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('idFoto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreFoto', models.CharField(max_length=100)),
                ('nombreArchivo', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
