# Generated by Django 4.0.5 on 2022-07-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_producto_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProducto',
            new_name='nombre',
        ),
    ]
