# Generated by Django 4.0.5 on 2022-07-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_rename_nombreproducto_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating Producto'),
        ),
    ]
